repos:
  # базовые проверки от создателей pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace      # удаляет лишние пробелы на концах строк
      - id: end-of-file-fixer        # добавляет пустую строку в конец файла
      - id: check-yaml               # проверяет синтаксис YAML файлов
      - id: check-added-large-files  # блокирует коммит огромных файлов (>500kb)
        args: ["--maxkb=1024"]
      - id: debug-statements         # проверяет, не забыл ли ты print() или breakpoint()
      - id: requirements-txt-fixer   # автоматически сортирует зависимости в файле в алфавитном порядке для улучшения читаемости и согласованности кода

#  # mypy
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v2.0.0
#    hooks:
#      - id: mypy
#        exclude: ^tests/
#        additional_dependencies: [streamlit]

  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.21
    hooks:
      # линтер
      - id: ruff-check
        types_or: [python, pyi, pyproject]
        args: [--fix]
      # форматер
      - id: ruff-format
        types_or: [python, pyi, pyproject]

  # hadolint - check Dockerfile
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
