name: CI Pipeline

# Настраиваем триггеры: когда запускать пайплайн
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Укажи свою версию, если она другая
          cache: "pip"           # ПРО-ФИШКА: кэшируем зависимости, чтобы CI работал за секунды, а не минуты

      # 3. Устанавливаем зависимости из твоего requirements.txt + инструменты для CI
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest

      # 4. Проверяем код  Ruff
      - name: Lint with Ruff
        run: |
          # Проверяем линтером на ошибки логики
          ruff check .
          # Проверяем форматтером, что код отформатирован (если нет - CI упадет с ошибкой)
          ruff format --check .

      # 5. Место под тесты (пока просто команда, чтобы убедиться, что pytest работает)
      - name: Run Tests
        run: |
          #pytest --version
          pytest ./tests/ -vv

      # 6. Проверка кода на уязвимости
      - name: Security check with Bandit
        run: |
          pip install bandit
          # -ll означает проверку уязвимостей только среднего и высокого уровня (чтобы не спамил по пустякам)
          # -r . рекурсивно проверяет все файлы в текущей папке
          bandit -r . -ll -ii

      # 7. Проверка зависимостей на известные дыры (CVE)
      - name: Dependency security audit
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt

      # 8. Линтинг Dockerfile (проверка на best practices)
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error # Опционально: падать только на критичных ошибках, а warning пропускать

      # 9. Проверяем, что Docker-образ успешно собирается
      - name: Build Docker Image
        run: |
          # Собираем образ и даем ему временное имя 'my-app-test'
          docker build -t my-app-test .
