name: CI Pipeline

# Настраиваем триггеры: когда запускать пайплайн
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # ==========================================
  # JOB 1: Проверка Python-кода
  # ==========================================
  python-test:
    name: Code & Security Checks
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем uv
      - name: Install uv and Python
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990
        with:
          python-version: "3.11"
          enable-cache: true
          # используем uv.lock для формирования ключа хеша для GH Actions (если хеш не изменился, то не нужно заново скачивать зависимости)
          cache-dependency-glob: "uv.lock"

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        # установка набора зависимостей, которые зафиксированы в uv.lock + ставим группу dev
        run: uv sync --frozen --group dev

      # 4. Проверяем код Ruff
      - name: Lint with Ruff
        run: |
          # Проверяем ошибки логики
          uv run ruff check .
          # Проверяем форматтером
          uv run ruff format --check .

      # 5. Прогоняем тесты через pytest
      - name: Run Pytest
        run: uv run pytest ./tests/ -vv

      # 6. Проверка кода на уязвимости
      - name: Security check with Bandit
        run: uvx bandit -c pyproject.toml -r .

      # 7. Проверка зависимостей на известные дыры (CVE)
      - name: Dependency security audit
        run: uvx pip-audit -r requirements.txt

  # ==========================================
  # JOB 2: Проверка Инфраструктуры (Docker)
  # ==========================================
  docker-checks:
    name: Docker Build Check
    runs-on: ubuntu-latest
    needs: python-test  # ждет успешного завершения 'python-tests'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Линтинг Dockerfile (проверка на best practices)
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error # Опционально: падать только на критичных ошибках, а warning пропускать

      # 2. Проверяем, что Docker-образ успешно собирается
      - name: Build Docker Image
        run: |
          # Собираем образ и даем ему временное имя 'my-app-test'
          docker build -t my-app-test .
